export const blocks = [
  { id: 0, color: "light" },
  { id: 1, color: "dark" },
  { id: 2, color: "light" },
  { id: 3, color: "dark" },
  { id: 4, color: "light" },
  { id: 5, color: "dark" },
  { id: 6, color: "light" },
  { id: 7, color: "dark" },
  { id: 8, color: "light" },
  { id: 9, color: "dark" },
  { id: 10, color: "light" },
  { id: 11, color: "dark" },
  { id: 12, color: "light" },
  { id: 13, color: "dark" },
  { id: 14, color: "light" },
  { id: 15, color: "dark" },
  { id: 16, color: "light" },
  { id: 17, color: "dark" },
  { id: 18, color: "light" },
  { id: 19, color: "dark" },
  { id: 20, color: "dark" },
  { id: 21, color: "light" },
  { id: 22, color: "dark" },
  { id: 23, color: "light" },
  { id: 24, color: "dark" },
  { id: 25, color: "light" },
  { id: 26, color: "dark" },
  { id: 27, color: "light" },
  { id: 28, color: "dark" },
  { id: 29, color: "light" },
  { id: 30, color: "dark" },
  { id: 31, color: "light" },
  { id: 32, color: "dark" },
  { id: 33, color: "light" },
  { id: 34, color: "dark" },
  { id: 35, color: "light" },
  { id: 36, color: "dark" },
  { id: 37, color: "light" },
  { id: 38, color: "dark" },
  { id: 39, color: "light" },
  { id: 40, color: "light" },
  { id: 41, color: "dark" },
  { id: 42, color: "light" },
  { id: 43, color: "dark" },
  { id: 44, color: "light" },
  { id: 45, color: "dark" },
  { id: 46, color: "light" },
  { id: 47, color: "dark" },
  { id: 48, color: "light" },
  { id: 49, color: "dark" },
  { id: 50, color: "light" },
  { id: 51, color: "dark" },
  { id: 52, color: "light" },
  { id: 53, color: "dark" },
  { id: 54, color: "light" },
  { id: 55, color: "dark" },
  { id: 56, color: "light" },
  { id: 57, color: "dark" },
  { id: 58, color: "light" },
  { id: 59, color: "dark" },
  { id: 60, color: "dark" },
  { id: 61, color: "light" },
  { id: 62, color: "dark" },
  { id: 63, color: "light" },
  { id: 64, color: "dark" },
  { id: 65, color: "light" },
  { id: 66, color: "dark" },
  { id: 67, color: "light" },
  { id: 68, color: "dark" },
  { id: 69, color: "light" },
  { id: 70, color: "dark" },
  { id: 71, color: "light" },
  { id: 72, color: "dark" },
  { id: 73, color: "light" },
  { id: 74, color: "dark" },
  { id: 75, color: "light" },
  { id: 76, color: "dark" },
  { id: 77, color: "light" },
  { id: 78, color: "dark" },
  { id: 79, color: "light" },
  { id: 80, color: "light" },
  { id: 81, color: "dark" },
  { id: 82, color: "light" },
  { id: 83, color: "dark" },
  { id: 84, color: "light" },
  { id: 85, color: "dark" },
  { id: 86, color: "light" },
  { id: 87, color: "dark" },
  { id: 88, color: "light" },
  { id: 89, color: "dark" },
  { id: 90, color: "light" },
  { id: 91, color: "dark" },
  { id: 92, color: "light" },
  { id: 93, color: "dark" },
  { id: 94, color: "light" },
  { id: 95, color: "dark" },
  { id: 96, color: "light" },
  { id: 97, color: "dark" },
  { id: 98, color: "light" },
  { id: 99, color: "dark" },
  { id: 100, color: "dark" },
  { id: 101, color: "light" },
  { id: 102, color: "dark" },
  { id: 103, color: "light" },
  { id: 104, color: "dark" },
  { id: 105, color: "light" },
  { id: 106, color: "dark" },
  { id: 107, color: "light" },
  { id: 108, color: "dark" },
  { id: 109, color: "light" },
  { id: 110, color: "dark" },
  { id: 111, color: "light" },
  { id: 112, color: "dark" },
  { id: 113, color: "light" },
  { id: 114, color: "dark" },
  { id: 115, color: "light" },
  { id: 116, color: "dark" },
  { id: 117, color: "light" },
  { id: 118, color: "dark" },
  { id: 119, color: "light" },
  { id: 120, color: "light" },
  { id: 121, color: "dark" },
  { id: 122, color: "light" },
  { id: 123, color: "dark" },
  { id: 124, color: "light" },
  { id: 125, color: "dark" },
  { id: 126, color: "light" },
  { id: 127, color: "dark" },
  { id: 128, color: "light" },
  { id: 129, color: "dark" },
  { id: 130, color: "light" },
  { id: 131, color: "dark" },
  { id: 132, color: "light" },
  { id: 133, color: "dark" },
  { id: 134, color: "light" },
  { id: 135, color: "dark" },
  { id: 136, color: "light" },
  { id: 137, color: "dark" },
  { id: 138, color: "light" },
  { id: 139, color: "dark" },
  { id: 140, color: "dark" },
  { id: 141, color: "light" },
  { id: 142, color: "dark" },
  { id: 143, color: "light" },
  { id: 144, color: "dark" },
  { id: 145, color: "light" },
  { id: 146, color: "dark" },
  { id: 147, color: "light" },
  { id: 148, color: "dark" },
  { id: 149, color: "light" },
  { id: 150, color: "dark" },
  { id: 151, color: "light" },
  { id: 152, color: "dark" },
  { id: 153, color: "light" },
  { id: 154, color: "dark" },
  { id: 155, color: "light" },
  { id: 156, color: "dark" },
  { id: 157, color: "light" },
  { id: 158, color: "dark" },
  { id: 159, color: "light" },
  { id: 160, color: "light" },
  { id: 161, color: "dark" },
  { id: 162, color: "light" },
  { id: 163, color: "dark" },
  { id: 164, color: "light" },
  { id: 165, color: "dark" },
  { id: 166, color: "light" },
  { id: 167, color: "dark" },
  { id: 168, color: "light" },
  { id: 169, color: "dark" },
  { id: 170, color: "light" },
  { id: 171, color: "dark" },
  { id: 172, color: "light" },
  { id: 173, color: "dark" },
  { id: 174, color: "light" },
  { id: 175, color: "dark" },
  { id: 176, color: "light" },
  { id: 177, color: "dark" },
  { id: 178, color: "light" },
  { id: 179, color: "dark" },
  { id: 180, color: "dark" },
  { id: 181, color: "light" },
  { id: 182, color: "dark" },
  { id: 183, color: "light" },
  { id: 184, color: "dark" },
  { id: 185, color: "light" },
  { id: 186, color: "dark" },
  { id: 187, color: "light" },
  { id: 188, color: "dark" },
  { id: 189, color: "light" },
  { id: 190, color: "dark" },
  { id: 191, color: "light" },
  { id: 192, color: "dark" },
  { id: 193, color: "light" },
  { id: 194, color: "dark" },
  { id: 195, color: "light" },
  { id: 196, color: "dark" },
  { id: 197, color: "light" },
  { id: 198, color: "dark" },
  { id: 199, color: "light" },
  { id: 200, color: "light" },
  { id: 201, color: "dark" },
  { id: 202, color: "light" },
  { id: 203, color: "dark" },
  { id: 204, color: "light" },
  { id: 205, color: "dark" },
  { id: 206, color: "light" },
  { id: 207, color: "dark" },
  { id: 208, color: "light" },
  { id: 209, color: "dark" },
  { id: 210, color: "light" },
  { id: 211, color: "dark" },
  { id: 212, color: "light" },
  { id: 213, color: "dark" },
  { id: 214, color: "light" },
  { id: 215, color: "dark" },
  { id: 216, color: "light" },
  { id: 217, color: "dark" },
  { id: 218, color: "light" },
  { id: 219, color: "dark" },
  { id: 220, color: "dark" },
  { id: 221, color: "light" },
  { id: 222, color: "dark" },
  { id: 223, color: "light" },
  { id: 224, color: "dark" },
  { id: 225, color: "light" },
  { id: 226, color: "dark" },
  { id: 227, color: "light" },
  { id: 228, color: "dark" },
  { id: 229, color: "light" },
  { id: 230, color: "dark" },
  { id: 231, color: "light" },
  { id: 232, color: "dark" },
  { id: 233, color: "light" },
  { id: 234, color: "dark" },
  { id: 235, color: "light" },
  { id: 236, color: "dark" },
  { id: 237, color: "light" },
  { id: 238, color: "dark" },
  { id: 239, color: "light" },
  { id: 240, color: "light" },
  { id: 241, color: "dark" },
  { id: 242, color: "light" },
  { id: 243, color: "dark" },
  { id: 244, color: "light" },
  { id: 245, color: "dark" },
  { id: 246, color: "light" },
  { id: 247, color: "dark" },
  { id: 248, color: "light" },
  { id: 249, color: "dark" },
  { id: 250, color: "light" },
  { id: 251, color: "dark" },
  { id: 252, color: "light" },
  { id: 253, color: "dark" },
  { id: 254, color: "light" },
  { id: 255, color: "dark" },
  { id: 256, color: "light" },
  { id: 257, color: "dark" },
  { id: 258, color: "light" },
  { id: 259, color: "dark" },
  { id: 260, color: "dark" },
  { id: 261, color: "light" },
  { id: 262, color: "dark" },
  { id: 263, color: "light" },
  { id: 264, color: "dark" },
  { id: 265, color: "light" },
  { id: 266, color: "dark" },
  { id: 267, color: "light" },
  { id: 268, color: "dark" },
  { id: 269, color: "light" },
  { id: 270, color: "dark" },
  { id: 271, color: "light" },
  { id: 272, color: "dark" },
  { id: 273, color: "light" },
  { id: 274, color: "dark" },
  { id: 275, color: "light" },
  { id: 276, color: "dark" },
  { id: 277, color: "light" },
  { id: 278, color: "dark" },
  { id: 279, color: "light" },
  { id: 280, color: "light" },
  { id: 281, color: "dark" },
  { id: 282, color: "light" },
  { id: 283, color: "dark" },
  { id: 284, color: "light" },
  { id: 285, color: "dark" },
  { id: 286, color: "light" },
  { id: 287, color: "dark" },
  { id: 288, color: "light" },
  { id: 289, color: "dark" },
  { id: 290, color: "light" },
  { id: 291, color: "dark" },
  { id: 292, color: "light" },
  { id: 293, color: "dark" },
  { id: 294, color: "light" },
  { id: 295, color: "dark" },
  { id: 296, color: "light" },
  { id: 297, color: "dark" },
  { id: 298, color: "light" },
  { id: 299, color: "dark" },
  { id: 300, color: "dark" },
  { id: 301, color: "light" },
  { id: 302, color: "dark" },
  { id: 303, color: "light" },
  { id: 304, color: "dark" },
  { id: 305, color: "light" },
  { id: 306, color: "dark" },
  { id: 307, color: "light" },
  { id: 308, color: "dark" },
  { id: 309, color: "light" },
  { id: 310, color: "dark" },
  { id: 311, color: "light" },
  { id: 312, color: "dark" },
  { id: 313, color: "light" },
  { id: 314, color: "dark" },
  { id: 315, color: "light" },
  { id: 316, color: "dark" },
  { id: 317, color: "light" },
  { id: 318, color: "dark" },
  { id: 319, color: "light" },
  { id: 320, color: "light" },
  { id: 321, color: "dark" },
  { id: 322, color: "light" },
  { id: 323, color: "dark" },
  { id: 324, color: "light" },
  { id: 325, color: "dark" },
  { id: 326, color: "light" },
  { id: 327, color: "dark" },
  { id: 328, color: "light" },
  { id: 329, color: "dark" },
  { id: 330, color: "light" },
  { id: 331, color: "dark" },
  { id: 332, color: "light" },
  { id: 333, color: "dark" },
  { id: 334, color: "light" },
  { id: 335, color: "dark" },
  { id: 336, color: "light" },
  { id: 337, color: "dark" },
  { id: 338, color: "light" },
  { id: 339, color: "dark" },
  { id: 340, color: "dark" },
  { id: 341, color: "light" },
  { id: 342, color: "dark" },
  { id: 343, color: "light" },
  { id: 344, color: "dark" },
  { id: 345, color: "light" },
  { id: 346, color: "dark" },
  { id: 347, color: "light" },
  { id: 348, color: "dark" },
  { id: 349, color: "light" },
  { id: 350, color: "dark" },
  { id: 351, color: "light" },
  { id: 352, color: "dark" },
  { id: 353, color: "light" },
  { id: 354, color: "dark" },
  { id: 355, color: "light" },
  { id: 356, color: "dark" },
  { id: 357, color: "light" },
  { id: 358, color: "dark" },
  { id: 359, color: "light" },
];

//// ==> this made my blocks array 
// for (var i = 0; i < blocks.length; i++) {
//   if (Math.floor(blocks[i].id / 20) % 2 === 0) {
//     if (blocks[i].id % 2 === 0) {
//       blocks[i].color = "light";
//     } else {
//       blocks[i].color = "dark";
//     }
//   } else {
//     if (blocks[i].id % 2 === 0) {
//       blocks[i].color = "dark";
//     } else {
//       blocks[i].color = "light";
//     }
//   }
// }
// console.log(JSON.stringify(blocks));

export const acceptedKey = new Set([
  "ArrowDown",
  "ArrowRight",
  "ArrowUp",
  "ArrowLeft",
]);

export const snakeStartBlocks = new Set([185, 184, 183]);

export const notAcceptedMove = {
  toRight: new Set([
    19, 39, 59, 79, 99, 119, 139, 159, 179, 199, 219, 239, 259, 279, 299, 319,
    339, 359,
  ]),
  toLeft: new Set([
    0, 20, 40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300,
    320, 340,
  ]),
  toUp: new Set([
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
  ]),
  toDown: new Set([
    340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354,
    355, 356, 357, 358, 359,
  ]),
};

export const firstAppleBlockNum = 194;